Bump Cert Manager to v1.5.5 and Kube Dashboard to v2.4.0

diff --git a/jobs/control/templates/bin/post-deploy b/jobs/control/templates/bin/post-deploy
--- a/jobs/control/templates/bin/post-deploy
+++ b/jobs/control/templates/bin/post-deploy
@@ -79,7 +79,11 @@ done)
 
 <% if p('dashboard.enabled') %>
 echo "[$(date)] $BIN/$$: applying kubernetes-dashboard configuration..."
-kubectl apply -f $JOB_DIR/k8s/dashboard.yml
+if ! kubectl apply -f $JOB_DIR/k8s/dashboard.yml; then
+  echo "Failed to update k8s dashboard in-place, trying to delete/create it..."
+  kubectl delete -f $JOB_DIR/k8s/dashboard.yml
+  kubectl apply -f $JOB_DIR/k8s/dashboard.yml
+fi
 kubectl delete -f $JOB_DIR/k8s/dashboard-acl.yml || true # might not exist yet...
 <% if p('dashboard.cluster-admin') %>
 kubectl apply -f $JOB_DIR/k8s/dashboard-acl.yml
